lib/all.a and Makefile changes
This way library files remain in lib/ and top-level Makefile
calls lib/ and src/ more or less the same way.

Also, make something.o should work in all subdirs.

While gcc strongly prefers something like libmini.a (or perhaps
even libc.a), let's keep it all.a for now.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -64,10 +64,34 @@ case "\$0" in
 	*) echo "\$0 may not be called from PATH" >&2; exit 1 ;;
 esac
 
-exec $cc \\
-	-nostdinc -I"\$base/lib/arch/$arch" -I"\$base/lib" \\
-	-fno-strict-aliasing -fno-asynchronous-unwind-tables \\
-	"\$@" -nostdlib -L"\$base" -ls -lgcc -ls
+unset compile output
+for _ in "\$@"; do
+	case "\$_" in
+		-c|-E|-S) compile=yes ;;
+		-o) output=yes ;;
+	esac
+done
+
+lib="\$base/lib/all.a"
+
+if [ -z "\$compile" -a ! -f "\$lib" ]; then
+	echo "\$0: missing \$lib" >&2
+	exit 1
+fi
+
+if [ -n "\$compile" ]; then
+	exec $cc \\
+		-nostdinc -I"\$base/lib/arch/$arch" -I"\$base/lib" \\
+		-fno-strict-aliasing -fno-asynchronous-unwind-tables \\
+		"\$@" -nostdlib
+elif [ -n "\$output" ]; then
+	exec $cc \\
+		-nostdinc -I"\$base/lib/arch/$arch" -I"\$base/lib" \\
+		-fno-strict-aliasing -fno-asynchronous-unwind-tables \\
+		"\$@" -nostdlib "\$lib" -lgcc
+else
+	exec $cc -nostdinc -nostdlib "\$@"
+fi
 END
 
 chmod a+x mini-cc
